[Setup]
AppName=OpenRestore
AppVersion=1.0.0
DefaultDirName={pf}\OpenRestore
DefaultGroupName=OpenRestore
OutputBaseFilename=OpenRestore_Setup
Compression=lzma2
SolidCompression=yes
ArchitecturesInstallIn64BitMode=x64

[Files]
; The main application files generated by PyInstaller
Source: "..\dist\OpenRestore\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; The iTunes offline installer (You must download iTunes64Setup.exe into this folder before compiling)
Source: "iTunes64Setup.exe"; DestDir: "{tmp}"; Flags: deleteafterinstall

[Icons]
Name: "{group}\OpenRestore"; Filename: "{app}\OpenRestore.exe"
Name: "{commondesktop}\OpenRestore"; Filename: "{app}\OpenRestore.exe"; Tasks: desktopicon

[Tasks]
Name: "desktopicon"; Description: "Create a desktop shortcut"; GroupDescription: "Additional icons:"

[Run]
; Run iTunes installer silently if Apple Mobile Device Support is not installed
Filename: "{tmp}\iTunes64Setup.exe"; Parameters: "/passive"; Check: NeedsiTunes; StatusMsg: "Установка драйверов Apple (iTunes)... Пожалуйста, подождите."
; Launch OpenRestore after installation
Filename: "{app}\OpenRestore.exe"; Description: "Запустить OpenRestore"; Flags: nowait postinstall skipifsilent

[Code]
function NeedsiTunes(): Boolean;
begin
  // Check if Apple Mobile Device Support is installed
  Result := not RegKeyExists(HKLM, 'SOFTWARE\Apple Inc.\Apple Mobile Device Support');
end;
